### ISSUE TITLE
GITHUB_ACCESS_TOKEN should be optional

### ISSUE THREAD

**Issue by ghost** [theanalyst/ceph-release-helper#2]
the github API can be read from anonymously. The only downside is the reduced number of API calls per hour or days, which should not be an issue in most cases. And it simplifies the usage a little.

**Comment by theanalyst** [comment]
Yes It should work without the api; I guess I can modify the code to do that.. I kind of hit the rate limit when I coded it initally (becuse about 5-6 runs ended up calling the api about 300 times)..

**Comment by ghost** [comment]
ah, right. then let's keep that mandatory: it's a lot more annoying to explain why it fails ;-)
